### ISSUE TITLE
IOS 10 with swift 3.0

### ISSUE THREAD

**Issue by tastyapp** [pixyzehn/PathMenu#13]
Now that swift 3.0 is released for devs, pathMenu can't compile.
Have you tried to convert your code to latest swift syntax ?
Thank you
<img width="256" alt="capture d ecran 2016-09-09 a 00 25 51" src="https://cloud.githubusercontent.com/assets/12382902/18369112/fc601368-7623-11e6-880c-8ed941ad6d67.png">

**Comment by pixyzehn** [comment]
Not yet. I think it's time to convert it. Thanks for letting me know it.

**Comment by pablomarcos** [comment]
Hi guys, any news about the Swift 3 conversion? Should I use another solution for short term?
I really appreciate your effort.
Kind regards

**Comment by pixyzehn** [comment]
I updated v2.0.0 for Swift3.0. Please check it:) Sorry for late.
