### ISSUE TITLE
The viewcontroller does not conform to protocol

### ISSUE THREAD

**Issue by GuilhermeaBorba** [pixyzehn/PathMenu#17]
<img width="1212" alt="captura de tela 2016-11-21 as 14 41 30" src="https://cloud.githubusercontent.com/assets/15332339/20491465/a2616ec0-aff8-11e6-90fc-1943f0dad5e6.png">

**Comment by Mo0812** [comment]
After updating PathMenu to gain Swift 3.0 compatibility, PathMenu has changed its delegate method names. Just have a look in the protocol of _PathMenuDelegate_ to detect the changes. If you change the method names you will get it working again.

![image](https://cloud.githubusercontent.com/assets/1677918/20814206/049d01a8-b819-11e6-940e-dc0525c17939.png)
