### ISSUE TITLE
Error while building/running when added through Cocoapods

### ISSUE THREAD

**Issue by surpher** [pixyzehn/PathMenu#2]
(null): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: unknown option character `X' in: -Xlinker

Xcode 6.2
iOS deployment Target: 8.0

**Comment by pixyzehn** [comment]
@surpher 
Thank you for your comment. I'll fix soon.

**Comment by pixyzehn** [comment]
@surpher 
I fixed that bug. Please confirm that again

**Comment by surpher** [comment]
Hey buddy. I can confirm I managed to get PathMenu version 1.0.1 working using Cocoapods. Good job, thanks!

**Comment by pixyzehn** [comment]
@surpher 
Hi, Glad to hear that. Thank you for letting me know.
